### ISSUE TITLE
Could you add decode demo?

### ISSUE THREAD

**Issue by nifflin** [dxhbiz/codec#1]
It's easy to use Encode, but  I couldn't decode bytes array to a struct.

Thanks, great job!

**Comment by dxhbiz** [comment]
`package main

import (
	"github.com/dxhbiz/codec"
	"fmt"
)

type Interest struct {
	Name string
}

type Person struct {
	Name string
	Sex int8
	Interests []Interest
	Age int8
}

func main()  {
	codecInfo := Person{
		Name: "test",
		Sex: 1,
		Interests: []Interest{
			{
				Name: "basketball",
			},
			{
				Name: "football",
			},
		},
		Age: 30,
	}
	buf, err := codec.Encode(&codecInfo)
	if err != nil {
		panic(err)
	}
	fmt.Println(buf)

	info := Person{}
	err = codec.Decode(buf, &info)
	fmt.Printf("%+v\n", info)
}`

**Comment by dxhbiz** [comment]
```go
package main

import (
	"github.com/dxhbiz/codec"
	"fmt"
)

type Interest struct {
	Name string
}

type Person struct {
	Name string
	Sex int8
	Interests []Interest
	Age int8
}

func main()  {
	personEncode := Person{
		Name: "test",
		Sex: 1,
		Interests: []Interest{
			{
				Name: "basketball",
			},
			{
				Name: "football",
			},
		},
		Age: 30,
	}
	buf, err := codec.Encode(&personEncode)
	if err != nil {
		panic(err)
	}
	fmt.Println(buf)

	personDecode := Person{}
	err = codec.Decode(buf, &personDecode)
	fmt.Printf("%+v\n", personDecode)
}
```
